// This JS file is a helper in order to correctly call API with country code

// Got the country code list from 'https://gist.github.com/maephisto/9228207'
// Edited the list so that we can search for country names and codes with functions below
var isoCountries = [
    {short: 'AF', long: 'Afghanistan'},
    {short: 'AX', long: 'Aland Islands'},
    {short: 'AL', long: 'Albania'},
    {short: 'DZ', long: 'Algeria'},
    {short: 'AS', long: 'American Samoa'},
    {short: 'AD', long: 'Andorra'},
    {short: 'AO', long: 'Angola'},
    {short: 'AI', long: 'Anguilla'},
    {short: 'AQ', long: 'Antarctica'},
    {short: 'AG', long: 'Antigua And Barbuda'},
    {short: 'AR', long: 'Argentina'},
    {short: 'AM', long: 'Armenia'},
    {short: 'AW', long: 'Aruba'},
    {short: 'AU', long: 'Australia'},
    {short: 'AT', long: 'Austria'},
    {short: 'AZ', long: 'Azerbaijan'},
    {short: 'BS', long: 'Bahamas'},
    {short: 'BH', long: 'Bahrain'},
    {short: 'BD', long: 'Bangladesh'},
    {short: 'BB', long: 'Barbados'},
    {short: 'BY', long: 'Belarus'},
    {short: 'BE', long: 'Belgium'},
    {short: 'BZ', long: 'Belize'},
    {short: 'BJ', long: 'Benin'},
    {short: 'BM', long: 'Bermuda'},
    {short: 'BT', long: 'Bhutan'},
    {short: 'BO', long: 'Bolivia'},
    {short: 'BA', long: 'Bosnia And Herzegovina'},
    {short: 'BW', long: 'Botswana'},
    {short: 'BV', long: 'Bouvet Island'},
    {short: 'BR', long: 'Brazil'},
    {short: 'IO', long: 'British Indian Ocean Territory'},
    {short: 'BN', long: 'Brunei Darussalam'},
    {short: 'BG', long: 'Bulgaria'},
    {short: 'BF', long: 'Burkina Faso'},
    {short: 'BI', long: 'Burundi'},
    {short: 'KH', long: 'Cambodia'},
    {short: 'CM', long: 'Cameroon'},
    {short: 'CA', long: 'Canada'},
    {short: 'CV', long: 'Cape Verde'},
    {short: 'KY', long: 'Cayman Islands'},
    {short: 'CF', long: 'Central African Republic'},
    {short: 'TD', long: 'Chad'},
    {short: 'CL', long: 'Chile'},
    {short: 'CN', long: 'China'},
    {short: 'CX', long: 'Christmas Island'},
    {short: 'CC', long: 'Cocos (Keeling) Islands'},
    {short: 'CO', long: 'Colombia'},
    {short: 'KM', long: 'Comoros'},
    {short: 'CG', long: 'Congo'},
    {short: 'CD', long: 'Congo, Democratic Republic'},
    {short: 'CK', long: 'Cook Islands'},
    {short: 'CR', long: 'Costa Rica'},
    {short: 'CI', long: 'Cote D\'Ivoire'},
    {short: 'HR', long: 'Croatia'},
    {short: 'CU', long: 'Cuba'},
    {short: 'CY', long: 'Cyprus'},
    {short: 'CZ', long: 'Czech Republic'},
    {short: 'DK', long: 'Denmark'},
    {short: 'DJ', long: 'Djibouti'},
    {short: 'DM', long: 'Dominica'},
    {short: 'DO', long: 'Dominican Republic'},
    {short: 'EC', long: 'Ecuador'},
    {short: 'EG', long: 'Egypt'},
    {short: 'SV', long: 'El Salvador'},
    {short: 'GQ', long: 'Equatorial Guinea'},
    {short: 'ER', long: 'Eritrea'},
    {short: 'EE', long: 'Estonia'},
    {short: 'ET', long: 'Ethiopia'},
    {short: 'FK', long: 'Falkland Islands (Malvinas)'},
    {short: 'FO', long: 'Faroe Islands'},
    {short: 'FJ', long: 'Fiji'},
    {short: 'FI', long: 'Finland'},
    {short: 'FR', long: 'France'},
    {short: 'GF', long: 'French Guiana'},
    {short: 'PF', long: 'French Polynesia'},
    {short: 'TF', long: 'French Southern Territories'},
    {short: 'GA', long: 'Gabon'},
    {short: 'GM', long: 'Gambia'},
    {short: 'GE', long: 'Georgia'},
    {short: 'DE', long: 'Germany'},
    {short: 'GH', long: 'Ghana'},
    {short: 'GI', long: 'Gibraltar'},
    {short: 'GR', long: 'Greece'},
    {short: 'GL', long: 'Greenland'},
    {short: 'GD', long: 'Grenada'},
    {short: 'GP', long: 'Guadeloupe'},
    {short: 'GU', long: 'Guam'},
    {short: 'GT', long: 'Guatemala'},
    {short: 'GG', long: 'Guernsey'},
    {short: 'GN', long: 'Guinea'},
    {short: 'GW', long: 'Guinea-Bissau'},
    {short: 'GY', long: 'Guyana'},
    {short: 'HT', long: 'Haiti'},
    {short: 'HM', long: 'Heard Island & Mcdonald Islands'},
    {short: 'VA', long: 'Holy See (Vatican City State)'},
    {short: 'HN', long: 'Honduras'},
    {short: 'HK', long: 'Hong Kong'},
    {short: 'HU', long: 'Hungary'},
    {short: 'IS', long: 'Iceland'},
    {short: 'IN', long: 'India'},
    {short: 'ID', long: 'Indonesia'},
    {short: 'IR', long: 'Iran, Islamic Republic Of'},
    {short: 'IQ', long: 'Iraq'},
    {short: 'IE', long: 'Ireland'},
    {short: 'IM', long: 'Isle Of Man'},
    {short: 'IL', long: 'Israel'},
    {short: 'IT', long: 'Italy'},
    {short: 'JM', long: 'Jamaica'},
    {short: 'JP', long: 'Japan'},
    {short: 'JE', long: 'Jersey'},
    {short: 'JO', long: 'Jordan'},
    {short: 'KZ', long: 'Kazakhstan'},
    {short: 'KE', long: 'Kenya'},
    {short: 'KI', long: 'Kiribati'},
    {short: 'KR', long: 'Korea'},
    {short: 'KW', long: 'Kuwait'},
    {short: 'KG', long: 'Kyrgyzstan'},
    {short: 'LA', long: 'Lao People\'s Democratic Republic'},
    {short: 'LV', long: 'Latvia'},
    {short: 'LB', long: 'Lebanon'},
    {short: 'LS', long: 'Lesotho'},
    {short: 'LR', long: 'Liberia'},
    {short: 'LY', long: 'Libyan Arab Jamahiriya'},
    {short: 'LI', long: 'Liechtenstein'},
    {short: 'LT', long: 'Lithuania'},
    {short: 'LU', long: 'Luxembourg'},
    {short: 'MO', long: 'Macao'},
    {short: 'MK', long: 'Macedonia'},
    {short: 'MG', long: 'Madagascar'},
    {short: 'MW', long: 'Malawi'},
    {short: 'MY', long: 'Malaysia'},
    {short: 'MV', long: 'Maldives'},
    {short: 'ML', long: 'Mali'},
    {short: 'MT', long: 'Malta'},
    {short: 'MH', long: 'Marshall Islands'},
    {short: 'MQ', long: 'Martinique'},
    {short: 'MR', long: 'Mauritania'},
    {short: 'MU', long: 'Mauritius'},
    {short: 'YT', long: 'Mayotte'},
    {short: 'MX', long: 'Mexico'},
    {short: 'FM', long: 'Micronesia, Federated States Of'},
    {short: 'MD', long: 'Moldova'},
    {short: 'MC', long: 'Monaco'},
    {short: 'MN', long: 'Mongolia'},
    {short: 'ME', long: 'Montenegro'},
    {short: 'MS', long: 'Montserrat'},
    {short: 'MA', long: 'Morocco'},
    {short: 'MZ', long: 'Mozambique'},
    {short: 'MM', long: 'Myanmar'},
    {short: 'NA', long: 'Namibia'},
    {short: 'NR', long: 'Nauru'},
    {short: 'NP', long: 'Nepal'},
    {short: 'NL', long: 'Netherlands'},
    {short: 'AN', long: 'Netherlands Antilles'},
    {short: 'NC', long: 'New Caledonia'},
    {short: 'NZ', long: 'New Zealand'},
    {short: 'NI', long: 'Nicaragua'},
    {short: 'NE', long: 'Niger'},
    {short: 'NG', long: 'Nigeria'},
    {short: 'NU', long: 'Niue'},
    {short: 'NF', long: 'Norfolk Island'},
    {short: 'MP', long: 'Northern Mariana Islands'},
    {short: 'NO', long: 'Norway'},
    {short: 'OM', long: 'Oman'},
    {short: 'PK', long: 'Pakistan'},
    {short: 'PW', long: 'Palau'},
    {short: 'PS', long: 'Palestinian Territory, Occupied'},
    {short: 'PA', long: 'Panama'},
    {short: 'PG', long: 'Papua New Guinea'},
    {short: 'PY', long: 'Paraguay'},
    {short: 'PE', long: 'Peru'},
    {short: 'PH', long: 'Philippines'},
    {short: 'PN', long: 'Pitcairn'},
    {short: 'PL', long: 'Poland'},
    {short: 'PT', long: 'Portugal'},
    {short: 'PR', long: 'Puerto Rico'},
    {short: 'QA', long: 'Qatar'},
    {short: 'RE', long: 'Reunion'},
    {short: 'RO', long: 'Romania'},
    {short: 'RU', long: 'Russian Federation'},
    {short: 'RW', long: 'Rwanda'},
    {short: 'BL', long: 'Saint Barthelemy'},
    {short: 'SH', long: 'Saint Helena'},
    {short: 'KN', long: 'Saint Kitts And Nevis'},
    {short: 'LC', long: 'Saint Lucia'},
    {short: 'MF', long: 'Saint Martin'},
    {short: 'PM', long: 'Saint Pierre And Miquelon'},
    {short: 'VC', long: 'Saint Vincent And Grenadines'},
    {short: 'WS', long: 'Samoa'},
    {short: 'SM', long: 'San Marino'},
    {short: 'ST', long: 'Sao Tome And Principe'},
    {short: 'SA', long: 'Saudi Arabia'},
    {short: 'SN', long: 'Senegal'},
    {short: 'RS', long: 'Serbia'},
    {short: 'SC', long: 'Seychelles'},
    {short: 'SL', long: 'Sierra Leone'},
    {short: 'SG', long: 'Singapore'},
    {short: 'SK', long: 'Slovakia'},
    {short: 'SI', long: 'Slovenia'},
    {short: 'SB', long: 'Solomon Islands'},
    {short: 'SO', long: 'Somalia'},
    {short: 'ZA', long: 'South Africa'},
    {short: 'GS', long: 'South Georgia And Sandwich Isl.'},
    {short: 'ES', long: 'Spain'},
    {short: 'LK', long: 'Sri Lanka'},
    {short: 'SD', long: 'Sudan'},
    {short: 'SR', long: 'Suriname'},
    {short: 'SJ', long: 'Svalbard And Jan Mayen'},
    {short: 'SZ', long: 'Swaziland'},
    {short: 'SE', long: 'Sweden'},
    {short: 'CH', long: 'Switzerland'},
    {short: 'SY', long: 'Syrian Arab Republic'},
    {short: 'TW', long: 'Taiwan'},
    {short: 'TJ', long: 'Tajikistan'},
    {short: 'TZ', long: 'Tanzania'},
    {short: 'TH', long: 'Thailand'},
    {short: 'TL', long: 'Timor-Leste'},
    {short: 'TG', long: 'Togo'},
    {short: 'TK', long: 'Tokelau'},
    {short: 'TO', long: 'Tonga'},
    {short: 'TT', long: 'Trinidad And Tobago'},
    {short: 'TN', long: 'Tunisia'},
    {short: 'TR', long: 'Turkey'},
    {short: 'TM', long: 'Turkmenistan'},
    {short: 'TC', long: 'Turks And Caicos Islands'},
    {short: 'TV', long: 'Tuvalu'},
    {short: 'UG', long: 'Uganda'},
    {short: 'UA', long: 'Ukraine'},
    {short: 'AE', long: 'United Arab Emirates'},
    {short: 'GB', long: 'United Kingdom'},
    {short: 'US', long: 'United States'},
    {short: 'UM', long: 'United States Outlying Islands'},
    {short: 'UY', long: 'Uruguay'},
    {short: 'UZ', long: 'Uzbekistan'},
    {short: 'VU', long: 'Vanuatu'},
    {short: 'VE', long: 'Venezuela'},
    {short: 'VN', long: 'Viet Nam'},
    {short: 'VG', long: 'Virgin Islands, British'},
    {short: 'VI', long: 'Virgin Islands, U.S.'},
    {short: 'WF', long: 'Wallis And Futuna'},
    {short: 'EH', long: 'Western Sahara'},
    {short: 'YE', long: 'Yemen'},
    {short: 'ZM', long: 'Zambia'},
    {short: 'ZW', long: 'Zimbabwe'}
];

// With the country name get the country code
function getCountryCode (countryName) {
    try {
        let longCountry = isoCountries.filter(country =>
            country.long.toLowerCase() === countryName.toLowerCase());
        return longCountry[0].short;
    } catch (error) {
        return false
    }
}

// With the country code get the country name
function getCountryName(countryCode) {
    try{
    let shortCountry = isoCountries.filter(country =>
        country.short.toLowerCase() === countryCode.toLowerCase());
    return shortCountry[0].long;
    } catch (error) {
        // No need to return false because validation will already be performed on the country code
        return countryCode
    }
}